# http://geekyplatypus.com/making-your-dockerised-php-application-even-better/
version: "2"

services:
  caddy:
    image: zzrot/alpine-caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ~/.caddy:/root/.caddy
    networks:
      - frontend

  node:
    build:
      dockerfile: .docker/Dockerfile-node
      context: ../
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
